### ISSUE TITLE
Menu Scene SIGSEGV GPUContextVulkan::BindSR

### ISSUE THREAD

**Issue by xenogenesi** [FlaxEngine/NetworkSample#2] opened 2022-05-09 23:24 UTC
I wanted to try the example but I have some problem with the menu scene with the 2d render apparently (attached logs)

Video card too old? (I'm not very familiar with Vulkan)

[Log_2022_05_10_01_04_06.txt](https://github.com/FlaxEngine/NetworkSample/files/8655948/Log_2022_05_10_01_04_06.txt)
[segvbt.log](https://github.com/FlaxEngine/NetworkSample/files/8655951/segvbt.log)

Any idea what's the problem? And how to solve it if possible?

**Comment by xenogenesi** [comment] 2022-05-11 09:20
The problem seems to occur only if `UICanvas` is set with` Screen space`, with that setting I don't see the menu even in the editor. Now I'm using the 1.3 branch version, but it has the same problem.

Over the weekend I will try the Windows version to see if with the same hardware it has the same problem.

Another problem is that when I press `Host` ENet fails with error:

```
[ 00:01:47.246 ]: [Error] Failed to initialize ENet host!
```

[Log_2022_05_11_11_05_30.txt](https://github.com/FlaxEngine/NetworkSample/files/8668502/Log_2022_05_11_11_05_30.txt)

**Comment by mafiesto4** [comment] 2022-05-13 17:37
`NVIDIA GeForce GTX 980 Ti` should work fine. Flax support for Vulkan on Linux has some issues that we are aware but this one might be harder to tackle. Thanks for reporting this!

**Comment by mafiesto4** [comment] 2022-05-13 18:17
It looks like the problem was, as you said with `UICanvas` set to `Screen Space`, but crash was caused by Blue Panel in that canvas.
Fixed in: https://github.com/FlaxEngine/FlaxEngine/commit/3d7d52e779fe40c0352870f5def19e9b98e3081d

**Comment by mafiesto4** [comment] 2022-05-13 18:18
If you still have issue with `ENet` feel free to open another issue. We did some testing of ENet on all supported platforms and I remember it worked nice on Linux (Ubuntu 18 and 20). Probably some debugging will be needed.

**Closed as completed** 2022-05-13 18:17 UTC
Labels: bug

**Comment by xenogenesi** [comment] 2022-05-13 20:49
Thanks for the fix, tried it, it works great.

For ENet two possible problems come to mind, incompatible system installed version (libenet7 1.3.13) or the fact that I am using the network interface configured as bridge (br0), I will try to understand this weekend.
